### ISSUE TITLE
Build not working on Mac OS 10.14.2

### ISSUE THREAD

**Issue by artemdinaburg** [trailofbits/cb-multios#50]
I get the following errors after build.sh:

```
-- Build files have been written to: /Users/artem/git/cb-multios/build
[465/11140] Linking C shared library include/tiny-AES128-C/libtiny-AES128-C.dylib
FAILED: include/tiny-AES128-C/libtiny-AES128-C.dylib
: && /usr/bin/clang  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -dynamiclib -Wl,-headerpad_max_install_names -m32 -o include/tiny-AES128-C/libtiny-AES128-C.dylib -install_name @rpath/libtiny-AES128-C.dylib include/tiny-AES128-C/CMakeFiles/tiny-AES128-C.dir/aes.c.o   && :
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "___memset_chk", referenced from:
      _AES128_CBC_encrypt_buffer in aes.c.o
      _AES128_CBC_decrypt_buffer in aes.c.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[474/11140] Building C object challenges/HeartThrob/CMakeFiles/HeartThrob_patched.dir/src/check.c.o
ninja: build stopped: subcommand failed.
```

**Comment by ekilmer** [comment]
Try the following:
- Remove the `build` directory to start fresh (or re-clone the repo)
- Execute 
```
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
```
which comes from here https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624

The pyenv team also recommends this if you have trouble building some Python versions: https://github.com/pyenv/pyenv/wiki/Common-build-problems (under the macOS header)

**Comment by artemdinaburg** [comment]
Confirm this builds. The errors turn into: ```ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)```
